/**
 * JRToolsUSA — Full 100-Product Seed File
 * Run: npx tsx scripts/seed-products.ts
 *
 * Requirements:
 *   npm install @supabase/supabase-js tsx dotenv
 *
 * Env vars needed (.env.local):
 *   NEXT_PUBLIC_SUPABASE_URL=
 *   SUPABASE_SERVICE_ROLE_KEY=
 */

import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// ─── Types ────────────────────────────────────────────────────────────────────

export type ProductSeed = {
  name:            string
  slug:            string
  brand:           string
  category:        string
  subcategory:     string
  model:           string
  description:     string
  price:           number       // cents
  compare_price:   number | null
  voltage:         string
  stock:           number
  badge:           'sale' | 'new' | 'hot' | null
  rating:          number
  review_count:    number
  images:          string[]     // placeholder — replace with Supabase Storage URLs
  active:          boolean
  metadata: {
    weight_lbs?:   number
    amps?:         number
    included?:     string[]
    warranty?:     string
    max_torque?:   string
    rpm?:          string
    blade_size?:   string
    disc_size?:    string
  }
}

// ─── Helper ───────────────────────────────────────────────────────────────────

const slug = (name: string) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

const img = (brand: string, model: string) =>
  [`/images/products/${brand.toLowerCase()}/${model.toLowerCase()}.jpg`]

// ─── 100 Products ─────────────────────────────────────────────────────────────

export const products: ProductSeed[] = [

  // ── DeWALT — 22 products ───────────────────────────────────────────────────

  {
    name: '20V MAX XR Brushless Hammer Drill Kit',
    slug: '20v-max-xr-brushless-hammer-drill-kit-dcd996p2',
    brand: 'DeWalt', category: 'drills', subcategory: 'hammer-drill',
    model: 'DCD996P2', voltage: '20V', price: 14900, compare_price: 18900,
    stock: 24, badge: 'sale', rating: 4.8, review_count: 312,
    description: 'Three-speed all-metal transmission delivers versatility for a wide range of applications. Brushless motor provides up to 57% more run time over brushed.',
    images: img('dewalt','DCD996P2'),
    metadata: { weight_lbs: 4.0, max_torque: '820 in-lbs', rpm: '0-2000', included: ['2x 5.0Ah batteries','charger','kit bag'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Brushless Impact Driver Kit',
    slug: '20v-max-xr-brushless-impact-driver-dcf887p2',
    brand: 'DeWalt', category: 'drills', subcategory: 'impact-driver',
    model: 'DCF887P2', voltage: '20V', price: 13900, compare_price: 16900,
    stock: 18, badge: 'sale', rating: 4.9, review_count: 478,
    description: 'Brushless motor delivers up to 1825 in-lbs of max torque. 3-speed settings with precision drive in speed 1 for accurate fastening.',
    images: img('dewalt','DCF887P2'),
    metadata: { weight_lbs: 2.2, max_torque: '1825 in-lbs', rpm: '0-3250', included: ['2x 5.0Ah batteries','charger','belt hook'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '60V MAX FLEXVOLT 7-1/4" Circular Saw Kit',
    slug: '60v-max-flexvolt-circular-saw-dcs575t2',
    brand: 'DeWalt', category: 'saws', subcategory: 'circular-saw',
    model: 'DCS575T2', voltage: '60V', price: 27900, compare_price: 34900,
    stock: 12, badge: 'sale', rating: 4.9, review_count: 203,
    description: 'The power of a 15-amp corded saw. FLEXVOLT 60V MAX battery delivers maximum power. 9-lb tool weight for reduced operator fatigue.',
    images: img('dewalt','DCS575T2'),
    metadata: { weight_lbs: 9.0, blade_size: '7-1/4"', rpm: '5800', included: ['2x 6.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '12" Sliding Compound Miter Saw',
    slug: '12in-sliding-compound-miter-saw-dws780',
    brand: 'DeWalt', category: 'saws', subcategory: 'miter-saw',
    model: 'DWS780', voltage: 'Corded', price: 59900, compare_price: 69900,
    stock: 6, badge: 'sale', rating: 4.9, review_count: 891,
    description: 'XPS cross-cut positioning system provides adjustment-free cut line indication for accurate and efficient cutting. 15-amp motor.',
    images: img('dewalt','DWS780'),
    metadata: { weight_lbs: 56.0, amps: 15, blade_size: '12"', rpm: '3800', included: ['blade','blade wrench','dust bag'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR 4-1/2" Angle Grinder Kit',
    slug: '20v-max-xr-angle-grinder-dcg412p2',
    brand: 'DeWalt', category: 'grinders', subcategory: 'angle-grinder',
    model: 'DCG412P2', voltage: '20V', price: 11900, compare_price: 14900,
    stock: 20, badge: 'sale', rating: 4.7, review_count: 278,
    description: 'High performance brushless motor provides up to 57% more run time. 8,000 RPM for fast material removal.',
    images: img('dewalt','DCG412P2'),
    metadata: { weight_lbs: 5.1, disc_size: '4-1/2"', rpm: '8000', included: ['2x 5.0Ah batteries','charger','side handle'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Reciprocating Saw Kit',
    slug: '20v-max-xr-reciprocating-saw-dcs367p1',
    brand: 'DeWalt', category: 'saws', subcategory: 'reciprocating-saw',
    model: 'DCS367P1', voltage: '20V', price: 16900, compare_price: 19900,
    stock: 15, badge: 'sale', rating: 4.8, review_count: 234,
    description: 'Compact and lightweight design at 7.5 lbs for reduced user fatigue. 1-1/8" stroke length for fast cutting speed.',
    images: img('dewalt','DCS367P1'),
    metadata: { weight_lbs: 7.5, rpm: '3000 spm', included: ['1x 5.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Jigsaw Kit',
    slug: '20v-max-xr-jigsaw-dcs334p1',
    brand: 'DeWalt', category: 'saws', subcategory: 'jigsaw',
    model: 'DCS334P1', voltage: '20V', price: 14900, compare_price: 17900,
    stock: 14, badge: 'sale', rating: 4.7, review_count: 167,
    description: 'Tool-free blade change for fast, convenient blade changes. 4-position orbital setting maximizes cutting application versatility.',
    images: img('dewalt','DCS334P1'),
    metadata: { weight_lbs: 4.7, rpm: '0-3200 spm', included: ['1x 5.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Orbital Sander Kit',
    slug: '20v-max-xr-orbital-sander-dcw210p1',
    brand: 'DeWalt', category: 'sanders', subcategory: 'random-orbit',
    model: 'DCW210P1', voltage: '20V', price: 13900, compare_price: 16900,
    stock: 22, badge: 'sale', rating: 4.7, review_count: 189,
    description: 'Brushless motor efficiently drives the sander for more consistent performance. Variable speed dial allows for application matching.',
    images: img('dewalt','DCW210P1'),
    metadata: { weight_lbs: 2.8, rpm: '8000-12000', included: ['1x 5.0Ah battery','charger','sanding pad'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Framing Nailer',
    slug: '20v-max-xr-framing-nailer-dcn21plm1',
    brand: 'DeWalt', category: 'nailers', subcategory: 'framing-nailer',
    model: 'DCN21PLM1', voltage: '20V', price: 32900, compare_price: null,
    stock: 8, badge: 'new', rating: 4.8, review_count: 124,
    description: 'Brushless motor with a dual-speed motor drive mechanism provides consistent driving in all conditions. Paper-collated nails 2" to 3-1/4".',
    images: img('dewalt','DCN21PLM1'),
    metadata: { weight_lbs: 8.8, included: ['1x 2.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '12V MAX Green Cross-Line Laser Level',
    slug: '12v-max-green-cross-line-laser-dw089lg',
    brand: 'DeWalt', category: 'measuring', subcategory: 'laser-level',
    model: 'DW089LG', voltage: 'Battery', price: 24900, compare_price: 29900,
    stock: 16, badge: 'sale', rating: 4.8, review_count: 167,
    description: 'Green laser is 4X brighter than standard red laser for superior visibility. Self-leveling within 4° for quick setup.',
    images: img('dewalt','DW089LG'),
    metadata: { weight_lbs: 2.2, included: ['batteries','carrying case'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V/60V FLEXVOLT 10-Tool Combo Kit',
    slug: '20v-60v-flexvolt-10-tool-combo-dck1020d2',
    brand: 'DeWalt', category: 'combo', subcategory: '10-tool',
    model: 'DCK1020D2', voltage: '20V/60V', price: 89900, compare_price: 109900,
    stock: 5, badge: 'sale', rating: 4.9, review_count: 67,
    description: 'Complete jobsite solution. Includes drill, impact driver, circular saw, reciprocating saw, jigsaw, oscillating tool, grinder, light, and more.',
    images: img('dewalt','DCK1020D2'),
    metadata: { weight_lbs: 48.0, included: ['2x 2.0Ah batteries','charger','kit bag'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Rotary Hammer SDS+ Kit',
    slug: '20v-max-xr-rotary-hammer-sds-dch273p2',
    brand: 'DeWalt', category: 'drills', subcategory: 'rotary-hammer',
    model: 'DCH273P2', voltage: '20V', price: 24900, compare_price: 29900,
    stock: 10, badge: 'sale', rating: 4.8, review_count: 145,
    description: 'Brushless motor provides 1.1 ft-lbs of impact energy for efficient drilling in concrete. 3-mode operation.',
    images: img('dewalt','DCH273P2'),
    metadata: { weight_lbs: 5.1, rpm: '0-1200', included: ['2x 5.0Ah batteries','charger','case'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Belt Sander Kit',
    slug: '20v-max-xr-belt-sander-dcw220p1',
    brand: 'DeWalt', category: 'sanders', subcategory: 'belt-sander',
    model: 'DCW220P1', voltage: '20V', price: 17900, compare_price: 21900,
    stock: 9, badge: 'sale', rating: 4.6, review_count: 98,
    description: '3x18 belt for high material removal rate. Brushless motor for increased runtime and power. Dust sealed switch for extended tool life.',
    images: img('dewalt','DCW220P1'),
    metadata: { weight_lbs: 6.2, rpm: '0-1600 spm', included: ['1x 5.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Brad Nailer Kit',
    slug: '20v-max-xr-brad-nailer-dcn680d1',
    brand: 'DeWalt', category: 'nailers', subcategory: 'brad-nailer',
    model: 'DCN680D1', voltage: '20V', price: 22900, compare_price: 26900,
    stock: 12, badge: 'sale', rating: 4.8, review_count: 203,
    description: 'Brushless motor drives 18-gauge brad nails from 5/8" to 2-1/8". Tool-free depth adjustment and jam release.',
    images: img('dewalt','DCN680D1'),
    metadata: { weight_lbs: 5.6, included: ['1x 2.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX Oscillating Multi-Tool Kit',
    slug: '20v-max-oscillating-multi-tool-dcs354p1',
    brand: 'DeWalt', category: 'accessories', subcategory: 'attachments',
    model: 'DCS354P1', voltage: '20V', price: 11900, compare_price: 14900,
    stock: 18, badge: 'sale', rating: 4.6, review_count: 198,
    description: 'Quick-change accessory system allows for tool-free accessory changes. Variable speed dial for application matching.',
    images: img('dewalt','DCS354P1'),
    metadata: { weight_lbs: 3.0, rpm: '10000-20000 opm', included: ['1x 5.0Ah battery','charger','accessories'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ATOMIC 20V MAX Compact Drill/Driver Kit',
    slug: 'atomic-20v-max-compact-drill-dcd708c2',
    brand: 'DeWalt', category: 'drills', subcategory: 'drill-driver',
    model: 'DCD708C2', voltage: '20V', price: 8900, compare_price: 10900,
    stock: 31, badge: 'sale', rating: 4.7, review_count: 521,
    description: 'Compact design fits in tight spaces. Brushless motor for increased runtime. 340 unit watts out for power.',
    images: img('dewalt','DCD708C2'),
    metadata: { weight_lbs: 2.3, max_torque: '340 UWO', rpm: '0-1650', included: ['2x 1.3Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR Finish Nailer 16-Gauge',
    slug: '20v-max-xr-finish-nailer-16ga-dcn660d1',
    brand: 'DeWalt', category: 'nailers', subcategory: 'finish-nailer',
    model: 'DCN660D1', voltage: '20V', price: 26900, compare_price: 31900,
    stock: 9, badge: 'sale', rating: 4.8, review_count: 156,
    description: 'Drives 16-gauge nails from 1-1/4" to 2-1/2". Brushless motor for consistent performance.',
    images: img('dewalt','DCN660D1'),
    metadata: { weight_lbs: 6.4, included: ['1x 2.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '165ft Laser Distance Measurer',
    slug: '165ft-laser-distance-measurer-dw099s',
    brand: 'DeWalt', category: 'measuring', subcategory: 'laser-measure',
    model: 'DW099S', voltage: 'Battery', price: 7900, compare_price: 9900,
    stock: 28, badge: 'sale', rating: 4.7, review_count: 312,
    description: '165 ft range with backlit LCD display. Calculates area, volume, and Pythagorean measurements.',
    images: img('dewalt','DW099S'),
    metadata: { weight_lbs: 0.3, included: ['batteries','case'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX XR 5-Tool Combo Kit',
    slug: '20v-max-xr-5-tool-combo-dck594p2',
    brand: 'DeWalt', category: 'combo', subcategory: '5-tool',
    model: 'DCK594P2', voltage: '20V', price: 57900, compare_price: 69900,
    stock: 7, badge: 'sale', rating: 4.9, review_count: 134,
    description: 'Includes drill, impact driver, circular saw, reciprocating saw, and work light. 2x 5.0Ah batteries included.',
    images: img('dewalt','DCK594P2'),
    metadata: { weight_lbs: 32.0, included: ['2x 5.0Ah batteries','charger','kit bag'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '9-Amp 4-1/2" Small Angle Grinder',
    slug: '9-amp-angle-grinder-dwe402',
    brand: 'DeWalt', category: 'grinders', subcategory: 'angle-grinder',
    model: 'DWE402', voltage: 'Corded', price: 7900, compare_price: 9900,
    stock: 24, badge: 'sale', rating: 4.6, review_count: 456,
    description: 'High-performance 9-amp motor. Dust ejection system for extended motor life in harsh jobsite conditions.',
    images: img('dewalt','DWE402'),
    metadata: { weight_lbs: 5.0, amps: 9, disc_size: '4-1/2"', rpm: '11000', warranty: '3-year limited' },
    active: true,
  },
  {
    name: '20V MAX 1/2" Impact Wrench Kit',
    slug: '20v-max-impact-wrench-dcf894p2',
    brand: 'DeWalt', category: 'drills', subcategory: 'impact-wrench',
    model: 'DCF894P2', voltage: '20V', price: 22900, compare_price: 27900,
    stock: 11, badge: 'sale', rating: 4.8, review_count: 187,
    description: '3-speed settings provide control in a variety of fastening applications. 330 ft-lbs of max breakaway torque.',
    images: img('dewalt','DCF894P2'),
    metadata: { weight_lbs: 3.4, max_torque: '330 ft-lbs', included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'Folding Locking Utility Knife',
    slug: 'folding-locking-utility-knife-dwht10035l',
    brand: 'DeWalt', category: 'accessories', subcategory: 'attachments',
    model: 'DWHT10035L', voltage: 'N/A', price: 1900, compare_price: null,
    stock: 75, badge: null, rating: 4.6, review_count: 892,
    description: 'Folding design with locking mechanism for safe transport. Quick blade change feature.',
    images: img('dewalt','DWHT10035L'),
    metadata: { weight_lbs: 0.3, warranty: '1-year' },
    active: true,
  },

  // ── Milwaukee — 19 products ────────────────────────────────────────────────

  {
    name: 'M18 FUEL 1/2" Hammer Drill/Driver',
    slug: 'm18-fuel-hammer-drill-2804-22',
    brand: 'Milwaukee', category: 'drills', subcategory: 'hammer-drill',
    model: '2804-22', voltage: '18V', price: 17900, compare_price: 21900,
    stock: 16, badge: 'sale', rating: 4.9, review_count: 387,
    description: 'POWERSTATE brushless motor delivers 1200 in-lbs of torque. REDLINK PLUS intelligence prevents overloads.',
    images: img('milwaukee','2804-22'),
    metadata: { weight_lbs: 4.5, max_torque: '1200 in-lbs', rpm: '0-2000', included: ['2x 5.0Ah batteries','charger','case'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL 1/4" Hex Impact Driver',
    slug: 'm18-fuel-impact-driver-2853-22',
    brand: 'Milwaukee', category: 'drills', subcategory: 'impact-driver',
    model: '2853-22', voltage: '18V', price: 16900, compare_price: null,
    stock: 22, badge: 'hot', rating: 4.9, review_count: 512,
    description: '4-mode drive control for precision fastening. POWERSTATE motor delivers 2000 in-lbs of torque.',
    images: img('milwaukee','2853-22'),
    metadata: { weight_lbs: 2.1, max_torque: '2000 in-lbs', rpm: '0-3600', included: ['2x 5.0Ah batteries','charger'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL 7-1/4" Circular Saw',
    slug: 'm18-fuel-circular-saw-2732-20',
    brand: 'Milwaukee', category: 'saws', subcategory: 'circular-saw',
    model: '2732-20', voltage: '18V', price: 24900, compare_price: null,
    stock: 11, badge: 'hot', rating: 4.8, review_count: 167,
    description: 'Delivers more power, faster cutting speed, and increased runtime than corded. 5800 RPM.',
    images: img('milwaukee','2732-20'),
    metadata: { weight_lbs: 9.2, blade_size: '7-1/4"', rpm: '5800', warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL 1/2" Impact Wrench w/ Friction Ring',
    slug: 'm18-fuel-impact-wrench-2863-22',
    brand: 'Milwaukee', category: 'drills', subcategory: 'impact-wrench',
    model: '2863-22', voltage: '18V', price: 28900, compare_price: null,
    stock: 9, badge: 'hot', rating: 4.9, review_count: 243,
    description: '1400 ft-lbs of breakaway torque. ONE-KEY compatible for customizable tool control.',
    images: img('milwaukee','2863-22'),
    metadata: { weight_lbs: 5.2, max_torque: '1400 ft-lbs', included: ['2x 5.0Ah batteries','charger'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL 4-1/2" / 5" Grinder Paddle Switch',
    slug: 'm18-fuel-grinder-paddle-2880-22',
    brand: 'Milwaukee', category: 'grinders', subcategory: 'angle-grinder',
    model: '2880-22', voltage: '18V', price: 22900, compare_price: 26900,
    stock: 14, badge: 'sale', rating: 4.9, review_count: 198,
    description: 'POWERSTATE brushless motor delivers 9,000 RPM with no load. Restart Protection prevents accidental startups.',
    images: img('milwaukee','2880-22'),
    metadata: { weight_lbs: 5.8, disc_size: '4-1/2"', rpm: '9000', included: ['2x 5.0Ah batteries','charger'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL Reciprocating Saw',
    slug: 'm18-fuel-reciprocating-saw-2821-20',
    brand: 'Milwaukee', category: 'saws', subcategory: 'reciprocating-saw',
    model: '2821-20', voltage: '18V', price: 19900, compare_price: null,
    stock: 13, badge: null, rating: 4.8, review_count: 156,
    description: '3,000 SPM variable speed for faster cutting. Tool-free blade change for quick blade swaps.',
    images: img('milwaukee','2821-20'),
    metadata: { weight_lbs: 7.3, rpm: '0-3000 spm', warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL 15-Gauge Angled Finish Nailer',
    slug: 'm18-fuel-finish-nailer-15ga-2742-20',
    brand: 'Milwaukee', category: 'nailers', subcategory: 'finish-nailer',
    model: '2742-20', voltage: '18V', price: 29900, compare_price: 34900,
    stock: 7, badge: 'sale', rating: 4.9, review_count: 87,
    description: 'Drives 15-gauge nails from 1-1/4" to 2-1/2". Zero ramp-up time for immediate driving power.',
    images: img('milwaukee','2742-20'),
    metadata: { weight_lbs: 7.5, warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 5" Random Orbit Sander',
    slug: 'm18-random-orbit-sander-2648-20',
    brand: 'Milwaukee', category: 'sanders', subcategory: 'random-orbit',
    model: '2648-20', voltage: '18V', price: 14900, compare_price: null,
    stock: 19, badge: 'hot', rating: 4.8, review_count: 143,
    description: '12,000 OPM for aggressive material removal. Variable speed control for application matching.',
    images: img('milwaukee','2648-20'),
    metadata: { weight_lbs: 2.6, rpm: '7000-12000', warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M12 Green 360° Cross-Line Laser Kit',
    slug: 'm12-green-360-cross-line-laser-3622-21',
    brand: 'Milwaukee', category: 'measuring', subcategory: 'laser-level',
    model: '3622-21', voltage: '12V', price: 27900, compare_price: null,
    stock: 14, badge: 'new', rating: 4.9, review_count: 134,
    description: 'Green beam is 4X brighter than red. Projects 360° horizontal line and 180° vertical lines simultaneously.',
    images: img('milwaukee','3622-21'),
    metadata: { weight_lbs: 1.8, included: ['battery','charger','carrying case'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 8-Tool Combo Kit',
    slug: 'm18-8-tool-combo-2695-28p',
    brand: 'Milwaukee', category: 'combo', subcategory: '8-tool',
    model: '2695-28P', voltage: '18V', price: 84900, compare_price: 99900,
    stock: 4, badge: 'hot', rating: 4.9, review_count: 54,
    description: 'Complete M18 system including drill, impact, circular saw, reciprocating saw, grinder, light, and more.',
    images: img('milwaukee','2695-28P'),
    metadata: { weight_lbs: 52.0, included: ['2x 5.0Ah batteries','charger','contractor bag'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL Rotary Hammer SDS-Plus',
    slug: 'm18-fuel-rotary-hammer-sds-2712-22',
    brand: 'Milwaukee', category: 'drills', subcategory: 'rotary-hammer',
    model: '2712-22', voltage: '18V', price: 34900, compare_price: 39900,
    stock: 8, badge: 'sale', rating: 4.9, review_count: 112,
    description: '2.0 ft-lbs of impact energy with 0-1100 RPM. AUTOSTOP control detects bind-up for safer operation.',
    images: img('milwaukee','2712-22'),
    metadata: { weight_lbs: 6.6, rpm: '0-1100', included: ['2x 5.0Ah batteries','charger','case'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL 6-1/2" Track Saw',
    slug: 'm18-fuel-track-saw-2831-20',
    brand: 'Milwaukee', category: 'saws', subcategory: 'circular-saw',
    model: '2831-20', voltage: '18V', price: 37900, compare_price: null,
    stock: 6, badge: 'new', rating: 4.8, review_count: 76,
    description: 'Compatible with standard 55mm guide rails. Delivers up to 385 linear feet per charge with 5.0Ah battery.',
    images: img('milwaukee','2831-20'),
    metadata: { weight_lbs: 8.4, blade_size: '6-1/2"', warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL 21° Framing Nailer',
    slug: 'm18-fuel-framing-nailer-2744-20',
    brand: 'Milwaukee', category: 'nailers', subcategory: 'framing-nailer',
    model: '2744-20', voltage: '18V', price: 37900, compare_price: 42900,
    stock: 6, badge: 'sale', rating: 4.9, review_count: 98,
    description: 'Drives 21° plastic-collated nails 2" to 3-1/4". Integrated dry-fire lockout prevents blank firing.',
    images: img('milwaukee','2744-20'),
    metadata: { weight_lbs: 9.1, warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M12 FUEL 1/2" Drill/Driver Kit',
    slug: 'm12-fuel-drill-driver-2503-22',
    brand: 'Milwaukee', category: 'drills', subcategory: 'drill-driver',
    model: '2503-22', voltage: '12V', price: 13900, compare_price: 16900,
    stock: 21, badge: 'sale', rating: 4.8, review_count: 287,
    description: 'Most compact drill on the market. POWERSTATE motor delivers 350 in-lbs of torque in a 5.9" length.',
    images: img('milwaukee','2503-22'),
    metadata: { weight_lbs: 1.7, max_torque: '350 in-lbs', included: ['2x 2.0Ah batteries','charger'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL Drywall Screw Gun',
    slug: 'm18-fuel-drywall-screw-gun-2866-20',
    brand: 'Milwaukee', category: 'accessories', subcategory: 'attachments',
    model: '2866-20', voltage: '18V', price: 17900, compare_price: null,
    stock: 12, badge: null, rating: 4.7, review_count: 143,
    description: 'Drives up to 35% more screws per charge than competitive tools. Auto-feed and collated compatible.',
    images: img('milwaukee','2866-20'),
    metadata: { weight_lbs: 4.1, warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL Jigsaw',
    slug: 'm18-fuel-jigsaw-2737-20',
    brand: 'Milwaukee', category: 'saws', subcategory: 'jigsaw',
    model: '2737-20', voltage: '18V', price: 19900, compare_price: 23900,
    stock: 10, badge: 'sale', rating: 4.8, review_count: 132,
    description: '4-orbital action settings. Anti-vibration system reduces vibrations for better control.',
    images: img('milwaukee','2737-20'),
    metadata: { weight_lbs: 5.4, rpm: '0-3500 spm', warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 FUEL Die Grinder',
    slug: 'm18-fuel-die-grinder-2784-20',
    brand: 'Milwaukee', category: 'grinders', subcategory: 'die-grinder',
    model: '2784-20', voltage: '18V', price: 16900, compare_price: null,
    stock: 11, badge: null, rating: 4.7, review_count: 98,
    description: '25,000 RPM no-load speed. Electronic speed control maintains consistent speed under load.',
    images: img('milwaukee','2784-20'),
    metadata: { weight_lbs: 2.9, rpm: '25000', warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 2-Tool Drill + Impact Driver Combo',
    slug: 'm18-2-tool-combo-2997-22',
    brand: 'Milwaukee', category: 'combo', subcategory: '2-tool',
    model: '2997-22', voltage: '18V', price: 29900, compare_price: 36900,
    stock: 18, badge: 'sale', rating: 4.9, review_count: 412,
    description: 'Includes M18 FUEL hammer drill and impact driver. Most popular starter combo for professionals.',
    images: img('milwaukee','2997-22'),
    metadata: { weight_lbs: 12.0, included: ['2x 5.0Ah batteries','charger','bag'], warranty: '5-year limited' },
    active: true,
  },
  {
    name: 'M18 Brad Nailer 18-Gauge',
    slug: 'm18-brad-nailer-18ga-2746-20',
    brand: 'Milwaukee', category: 'nailers', subcategory: 'brad-nailer',
    model: '2746-20', voltage: '18V', price: 19900, compare_price: 23900,
    stock: 11, badge: 'sale', rating: 4.8, review_count: 167,
    description: 'Drives 18-gauge brad nails 5/8" to 2-1/8". Precise placement tool with 360° adjustable exhaust.',
    images: img('milwaukee','2746-20'),
    metadata: { weight_lbs: 5.2, warranty: '5-year limited' },
    active: true,
  },

  // ── Makita — 17 products ───────────────────────────────────────────────────

  {
    name: '18V LXT Brushless 1/2" Driver-Drill Kit',
    slug: '18v-lxt-brushless-driver-drill-xph12t',
    brand: 'Makita', category: 'drills', subcategory: 'drill-driver',
    model: 'XPH12T', voltage: '18V', price: 13500, compare_price: 15900,
    stock: 17, badge: 'sale', rating: 4.7, review_count: 175,
    description: 'BL Brushless motor with faster speed, longer run time, and increased motor life. 530 in-lbs of torque.',
    images: img('makita','XPH12T'),
    metadata: { weight_lbs: 4.0, max_torque: '530 in-lbs', rpm: '0-2000', included: ['2x 5.0Ah batteries','charger','case'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT 6-1/2" Brushless Circular Saw Kit',
    slug: '18v-lxt-circular-saw-xss02t',
    brand: 'Makita', category: 'saws', subcategory: 'circular-saw',
    model: 'XSS02T', voltage: '18V', price: 18900, compare_price: 22900,
    stock: 13, badge: 'sale', rating: 4.7, review_count: 134,
    description: 'BL Brushless motor delivers 5,000 RPM. Compact design at 7.8 lbs for reduced operator fatigue.',
    images: img('makita','XSS02T'),
    metadata: { weight_lbs: 7.8, blade_size: '6-1/2"', rpm: '5000', included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT 5" Brushless Angle Grinder Kit',
    slug: '18v-lxt-angle-grinder-xag04t',
    brand: 'Makita', category: 'grinders', subcategory: 'angle-grinder',
    model: 'XAG04T', voltage: '18V', price: 16900, compare_price: 19900,
    stock: 15, badge: 'sale', rating: 4.7, review_count: 143,
    description: 'BL Brushless motor delivers 8,500 RPM. Tool-less wheel guard adjustment for quick changes.',
    images: img('makita','XAG04T'),
    metadata: { weight_lbs: 5.1, disc_size: '5"', rpm: '8500', included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Jigsaw (Tool Only)',
    slug: '18v-lxt-jigsaw-xvj03z',
    brand: 'Makita', category: 'saws', subcategory: 'jigsaw',
    model: 'XVJ03Z', voltage: '18V', price: 12900, compare_price: 15900,
    stock: 14, badge: 'sale', rating: 4.6, review_count: 112,
    description: '4-stage orbital action. Variable speed 0-2600 SPM. Tool-less blade change.',
    images: img('makita','XVJ03Z'),
    metadata: { weight_lbs: 4.9, rpm: '0-2600 spm', warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Brad Nailer Kit',
    slug: '18v-lxt-brad-nailer-xnb01t',
    brand: 'Makita', category: 'nailers', subcategory: 'brad-nailer',
    model: 'XNB01T', voltage: '18V', price: 22900, compare_price: null,
    stock: 9, badge: null, rating: 4.7, review_count: 76,
    description: 'Drives 18-gauge brad nails from 5/8" to 2". Spring-loaded nail chamber for easy jam removal.',
    images: img('makita','XNB01T'),
    metadata: { weight_lbs: 5.9, included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT 5" Random Orbit Sander Kit',
    slug: '18v-lxt-random-orbit-sander-xob01t',
    brand: 'Makita', category: 'sanders', subcategory: 'random-orbit',
    model: 'XOB01T', voltage: '18V', price: 11900, compare_price: 13900,
    stock: 16, badge: 'sale', rating: 4.6, review_count: 98,
    description: 'Variable speed control dial allows operator to match the sanding speed to the application.',
    images: img('makita','XOB01T'),
    metadata: { weight_lbs: 2.4, rpm: '4000-11000', included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT 5-Tool Combo Kit',
    slug: '18v-lxt-5-tool-combo-xt505s',
    brand: 'Makita', category: 'combo', subcategory: '5-tool',
    model: 'XT505S', voltage: '18V', price: 59900, compare_price: 72900,
    stock: 5, badge: 'sale', rating: 4.8, review_count: 89,
    description: 'Includes hammer drill, impact driver, circular saw, reciprocating saw, and flashlight.',
    images: img('makita','XT505S'),
    metadata: { weight_lbs: 28.0, included: ['2x 3.0Ah batteries','charger','bag'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Reciprocating Saw Kit',
    slug: '18v-lxt-reciprocating-saw-xrj04t',
    brand: 'Makita', category: 'saws', subcategory: 'reciprocating-saw',
    model: 'XRJ04T', voltage: '18V', price: 16900, compare_price: 19900,
    stock: 11, badge: 'sale', rating: 4.7, review_count: 123,
    description: 'Variable 3-speed 0-3,000 SPM. Tool-less blade change with 4-position shoe for extended blade and shoe life.',
    images: img('makita','XRJ04T'),
    metadata: { weight_lbs: 7.9, rpm: '0-3000 spm', included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '40V Max XGT Brushless Hammer Drill Kit',
    slug: '40v-max-xgt-hammer-drill-hp001gt201',
    brand: 'Makita', category: 'drills', subcategory: 'hammer-drill',
    model: 'HP001GT201', voltage: '40V', price: 27900, compare_price: null,
    stock: 8, badge: 'new', rating: 4.9, review_count: 54,
    description: 'XGT 40V Max platform delivers more power for demanding applications. 1,300 in-lbs of torque.',
    images: img('makita','HP001GT201'),
    metadata: { weight_lbs: 5.2, max_torque: '1300 in-lbs', included: ['2x 4.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Impact Driver Kit',
    slug: '18v-lxt-impact-driver-xdt16t',
    brand: 'Makita', category: 'drills', subcategory: 'impact-driver',
    model: 'XDT16T', voltage: '18V', price: 12900, compare_price: 14900,
    stock: 20, badge: 'sale', rating: 4.8, review_count: 298,
    description: '4-speed BL brushless motor with 1,600 in-lbs of max torque and 4,000 IPM.',
    images: img('makita','XDT16T'),
    metadata: { weight_lbs: 2.2, max_torque: '1600 in-lbs', included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Rotary Hammer SDS-Plus Kit',
    slug: '18v-lxt-rotary-hammer-xrh06pt',
    brand: 'Makita', category: 'drills', subcategory: 'rotary-hammer',
    model: 'XRH06PT', voltage: '18V', price: 29900, compare_price: 34900,
    stock: 7, badge: 'sale', rating: 4.8, review_count: 87,
    description: '1.1 ft-lbs of impact energy. 3-mode operation for drilling, hammer drilling, and chiseling.',
    images: img('makita','XRH06PT'),
    metadata: { weight_lbs: 6.4, rpm: '0-1200', included: ['2x 5.0Ah batteries','charger','case'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Finish Nailer 16-Gauge Kit',
    slug: '18v-lxt-finish-nailer-16ga-xnb02t',
    brand: 'Makita', category: 'nailers', subcategory: 'finish-nailer',
    model: 'XNB02T', voltage: '18V', price: 24900, compare_price: 28900,
    stock: 8, badge: 'sale', rating: 4.7, review_count: 112,
    description: 'Drives 16-gauge straight finish nails 1-1/4" to 2-1/2". Dry-fire lockout prevents firing when magazine is empty.',
    images: img('makita','XNB02T'),
    metadata: { weight_lbs: 7.2, included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Detail Sander Kit',
    slug: '18v-lxt-detail-sander-xos05t',
    brand: 'Makita', category: 'sanders', subcategory: 'detail-sander',
    model: 'XOS05T', voltage: '18V', price: 9900, compare_price: 12900,
    stock: 14, badge: 'sale', rating: 4.5, review_count: 87,
    description: 'Variable speed 6,000-12,000 OPM. Compact triangular sanding pad for tight spaces.',
    images: img('makita','XOS05T'),
    metadata: { weight_lbs: 1.6, rpm: '6000-12000', included: ['2x 3.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT 2-Pc Combo Drill & Impact Kit',
    slug: '18v-lxt-2pc-combo-xt269t',
    brand: 'Makita', category: 'combo', subcategory: '2-tool',
    model: 'XT269T', voltage: '18V', price: 23900, compare_price: 28900,
    stock: 16, badge: 'sale', rating: 4.8, review_count: 312,
    description: 'Includes 18V LXT hammer drill and impact driver. Perfect starter set for LXT platform.',
    images: img('makita','XT269T'),
    metadata: { weight_lbs: 9.0, included: ['2x 5.0Ah batteries','charger','bag'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Cordless Router Kit',
    slug: '18v-lxt-router-xtr01t7',
    brand: 'Makita', category: 'accessories', subcategory: 'attachments',
    model: 'XTR01T7', voltage: '18V', price: 28900, compare_price: null,
    stock: 6, badge: 'new', rating: 4.8, review_count: 65,
    description: 'Variable speed 10,000-30,000 RPM. Compatible with 1/4" collet router bits.',
    images: img('makita','XTR01T7'),
    metadata: { weight_lbs: 4.4, rpm: '10000-30000', included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '18V LXT Laser Distance Measurer',
    slug: '18v-lxt-laser-distance-measurer-ld050p',
    brand: 'Makita', category: 'measuring', subcategory: 'laser-measure',
    model: 'LD050P', voltage: 'Battery', price: 6900, compare_price: 8900,
    stock: 22, badge: 'sale', rating: 4.6, review_count: 134,
    description: '165ft range. Calculate distance, area and volume. IP54 water and dust resistant.',
    images: img('makita','LD050P'),
    metadata: { weight_lbs: 0.3, included: ['batteries'], warranty: '1-year limited' },
    active: true,
  },
  {
    name: '18V LXT Drywall Screwdriver Kit',
    slug: '18v-lxt-drywall-screwdriver-xsf03t',
    brand: 'Makita', category: 'accessories', subcategory: 'attachments',
    model: 'XSF03T', voltage: '18V', price: 14900, compare_price: 17900,
    stock: 9, badge: 'sale', rating: 4.6, review_count: 76,
    description: 'Depth adjustment for consistent screw depth setting. Auto-stop clutch prevents overdriving.',
    images: img('makita','XSF03T'),
    metadata: { weight_lbs: 3.3, rpm: '0-4500', included: ['2x 5.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },

  // ── Bosch — 14 products ────────────────────────────────────────────────────

  {
    name: '18V EC Brushless 1/2" Hammer Drill Kit',
    slug: '18v-ec-brushless-hammer-drill-gsr18v-190b22',
    brand: 'Bosch', category: 'drills', subcategory: 'hammer-drill',
    model: 'GSR18V-190B22', voltage: '18V', price: 15900, compare_price: 18900,
    stock: 13, badge: 'sale', rating: 4.7, review_count: 198,
    description: '1,900 RPM and 530 in-lbs of torque. Brushless motor for longer tool life.',
    images: img('bosch','GSR18V-190B22'),
    metadata: { weight_lbs: 3.7, max_torque: '530 in-lbs', rpm: '0-1900', included: ['2x 4.0Ah batteries','charger'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '12V Max EC Brushless Drill/Driver Kit',
    slug: '12v-max-ec-brushless-drill-ps32-02',
    brand: 'Bosch', category: 'drills', subcategory: 'drill-driver',
    model: 'PS32-02', voltage: '12V', price: 8900, compare_price: null,
    stock: 19, badge: 'new', rating: 4.6, review_count: 98,
    description: 'Most compact 12V drill at 5.6 inches long. 265 in-lbs of torque.',
    images: img('bosch','PS32-02'),
    metadata: { weight_lbs: 1.5, max_torque: '265 in-lbs', included: ['2x 2.0Ah batteries','charger'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '11-Amp 4-1/2" Angle Grinder',
    slug: '11-amp-angle-grinder-1375a',
    brand: 'Bosch', category: 'grinders', subcategory: 'angle-grinder',
    model: '1375A', voltage: 'Corded', price: 8900, compare_price: null,
    stock: 27, badge: null, rating: 4.5, review_count: 267,
    description: 'Narrow grip zone provides optimal balance and control. Kickback Chip for added protection.',
    images: img('bosch','1375A'),
    metadata: { weight_lbs: 4.9, amps: 11, disc_size: '4-1/2"', rpm: '11500', warranty: '1-year full' },
    active: true,
  },
  {
    name: '330ft Laser Distance Measurer',
    slug: '330ft-laser-distance-measurer-glm165-40',
    brand: 'Bosch', category: 'measuring', subcategory: 'laser-measure',
    model: 'GLM165-40', voltage: 'Battery', price: 8900, compare_price: 10900,
    stock: 31, badge: 'sale', rating: 4.7, review_count: 312,
    description: '330 ft range. Backlit screen for low-light conditions. Bluetooth connectivity.',
    images: img('bosch','GLM165-40'),
    metadata: { weight_lbs: 0.3, included: ['batteries'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '18V Reciprocating Saw Kit',
    slug: '18v-reciprocating-saw-clpk700b2',
    brand: 'Bosch', category: 'saws', subcategory: 'reciprocating-saw',
    model: 'GSA18V-LI', voltage: '18V', price: 14900, compare_price: 17900,
    stock: 12, badge: 'sale', rating: 4.6, review_count: 145,
    description: 'Compact 18V recip saw. Variable speed trigger. Tool-less blade change.',
    images: img('bosch','GSA18V-LI'),
    metadata: { weight_lbs: 5.3, rpm: '0-3000 spm', included: ['2x 4.0Ah batteries','charger'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '18V Jigsaw Kit',
    slug: '18v-jigsaw-gst18v-55-li-h',
    brand: 'Bosch', category: 'saws', subcategory: 'jigsaw',
    model: 'GST18V-55N', voltage: '18V', price: 13900, compare_price: 16900,
    stock: 10, badge: 'sale', rating: 4.6, review_count: 112,
    description: 'Barrel grip for better maneuverability. 4 orbital settings. Variable speed 0-3,200 SPM.',
    images: img('bosch','GST18V-55N'),
    metadata: { weight_lbs: 4.6, rpm: '0-3200 spm', included: ['2x 4.0Ah batteries','charger'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '18V Cordless Rotary Hammer SDS-Plus',
    slug: '18v-rotary-hammer-sds-gbh18v-26',
    brand: 'Bosch', category: 'drills', subcategory: 'rotary-hammer',
    model: 'GBH18V-26', voltage: '18V', price: 28900, compare_price: 32900,
    stock: 7, badge: 'sale', rating: 4.8, review_count: 87,
    description: '2.0 ft-lbs of impact energy. KickBack Control for added safety. 3 operation modes.',
    images: img('bosch','GBH18V-26'),
    metadata: { weight_lbs: 6.3, rpm: '0-900', included: ['2x 4.0Ah batteries','charger'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '360° Cross-Line Laser Level Kit',
    slug: '360-cross-line-laser-level-gll3-330cg',
    brand: 'Bosch', category: 'measuring', subcategory: 'laser-level',
    model: 'GLL3-330CG', voltage: 'Battery', price: 21900, compare_price: 25900,
    stock: 11, badge: 'sale', rating: 4.7, review_count: 145,
    description: 'Green beam 360° with Bluetooth enabled. App-connected for expanded functionality.',
    images: img('bosch','GLL3-330CG'),
    metadata: { weight_lbs: 2.1, included: ['batteries','mount','case'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '18V 5" Random Orbit Sander',
    slug: '18v-5in-random-orbit-sander-gex18v-5',
    brand: 'Bosch', category: 'sanders', subcategory: 'random-orbit',
    model: 'GEX18V-5', voltage: '18V', price: 13900, compare_price: null,
    stock: 14, badge: null, rating: 4.6, review_count: 78,
    description: 'Microfilter system captures fine dust particles. Variable speed control dial.',
    images: img('bosch','GEX18V-5'),
    metadata: { weight_lbs: 3.2, rpm: '7500-12000', warranty: '1-year full' },
    active: true,
  },
  {
    name: '18V 2-Tool Combo Drill + Driver',
    slug: '18v-2-tool-combo-cbk240-02',
    brand: 'Bosch', category: 'combo', subcategory: '2-tool',
    model: 'CBK240-02', voltage: '18V', price: 21900, compare_price: 26900,
    stock: 13, badge: 'sale', rating: 4.7, review_count: 234,
    description: 'Drill/driver and impact driver combo. Both under 3 lbs for reduced fatigue.',
    images: img('bosch','CBK240-02'),
    metadata: { weight_lbs: 8.0, included: ['2x 2.0Ah batteries','charger'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '12-Amp Corded Belt Sander 3x21"',
    slug: '12-amp-belt-sander-1274d',
    brand: 'Bosch', category: 'sanders', subcategory: 'belt-sander',
    model: '1274D', voltage: 'Corded', price: 12900, compare_price: 14900,
    stock: 11, badge: 'sale', rating: 4.5, review_count: 156,
    description: '12-amp motor. Constant Response circuitry maintains speed under load.',
    images: img('bosch','1274D'),
    metadata: { weight_lbs: 9.1, amps: 12, rpm: '820-1470 spm', warranty: '1-year full' },
    active: true,
  },
  {
    name: '5-Inch Stud Sensor',
    slug: '5-inch-stud-sensor-gms120',
    brand: 'Bosch', category: 'measuring', subcategory: 'stud-finder',
    model: 'GMS120', voltage: 'Battery', price: 3900, compare_price: null,
    stock: 45, badge: null, rating: 4.4, review_count: 445,
    description: 'Detects wood and metal studs up to 1-1/2 inches. AC detection for live wiring.',
    images: img('bosch','GMS120'),
    metadata: { weight_lbs: 0.4, included: ['batteries'], warranty: '1-year full' },
    active: true,
  },
  {
    name: '18V Framing Nailer',
    slug: '18v-framing-nailer-gfn18v-16hn',
    brand: 'Bosch', category: 'nailers', subcategory: 'framing-nailer',
    model: 'GFN18V-16HN', voltage: '18V', price: 27900, compare_price: 31900,
    stock: 8, badge: 'sale', rating: 4.7, review_count: 76,
    description: 'Drives 16-degree coil nails 1-1/4" to 3-1/4". No ramp-up time for immediate driving.',
    images: img('bosch','GFN18V-16HN'),
    metadata: { weight_lbs: 8.3, warranty: '1-year full' },
    active: true,
  },
  {
    name: '18V 4-Tool Combo Kit',
    slug: '18v-4-tool-combo-clpk420-02',
    brand: 'Bosch', category: 'combo', subcategory: '4-tool',
    model: 'CLPK420-02', voltage: '18V', price: 37900, compare_price: 45900,
    stock: 7, badge: 'sale', rating: 4.7, review_count: 143,
    description: 'Drill, impact driver, circular saw, and flashlight. Great value 4-tool kit.',
    images: img('bosch','CLPK420-02'),
    metadata: { weight_lbs: 18.0, included: ['2x 4.0Ah batteries','charger','bag'], warranty: '1-year full' },
    active: true,
  },

  // ── Ridgid — 11 products ───────────────────────────────────────────────────

  {
    name: '18V Brushless 1/2" Drill/Driver Kit',
    slug: '18v-brushless-drill-driver-r9702',
    brand: 'Ridgid', category: 'drills', subcategory: 'drill-driver',
    model: 'R9702', voltage: '18V', price: 11900, compare_price: null,
    stock: 14, badge: null, rating: 4.7, review_count: 86,
    description: 'Lifetime Service Agreement — free parts and service for life. 500 in-lbs of torque.',
    images: img('ridgid','R9702'),
    metadata: { max_torque: '500 in-lbs', rpm: '0-1900', included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V Brushless Impact Driver Kit',
    slug: '18v-brushless-impact-driver-r87014',
    brand: 'Ridgid', category: 'drills', subcategory: 'impact-driver',
    model: 'R87014', voltage: '18V', price: 10900, compare_price: 13900,
    stock: 15, badge: 'sale', rating: 4.6, review_count: 112,
    description: '1,800 in-lbs of torque. OFT (Optimum Fastening Technology) for a precise finish.',
    images: img('ridgid','R87014'),
    metadata: { max_torque: '1800 in-lbs', included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V 7-1/4" Circular Saw Kit',
    slug: '18v-circular-saw-r8653',
    brand: 'Ridgid', category: 'saws', subcategory: 'circular-saw',
    model: 'R8653', voltage: '18V', price: 14900, compare_price: 17900,
    stock: 11, badge: 'sale', rating: 4.6, review_count: 87,
    description: '5,200 RPM motor. Magnesium shoe for durability and reduced weight.',
    images: img('ridgid','R8653'),
    metadata: { blade_size: '7-1/4"', rpm: '5200', included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V Reciprocating Saw Kit',
    slug: '18v-reciprocating-saw-r8641b',
    brand: 'Ridgid', category: 'saws', subcategory: 'reciprocating-saw',
    model: 'R8641B', voltage: '18V', price: 12900, compare_price: null,
    stock: 10, badge: null, rating: 4.5, review_count: 67,
    description: '4-position adjustable shoe for extended blade life. Pivoting head for greater cutting ability.',
    images: img('ridgid','R8641B'),
    metadata: { rpm: '0-3000 spm', included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V 4-1/2" Angle Grinder Kit',
    slug: '18v-angle-grinder-r86040b',
    brand: 'Ridgid', category: 'grinders', subcategory: 'angle-grinder',
    model: 'R86040B', voltage: '18V', price: 9900, compare_price: 12900,
    stock: 13, badge: 'sale', rating: 4.5, review_count: 98,
    description: 'Brushless motor for more power and runtime. 8,500 RPM no-load speed.',
    images: img('ridgid','R86040B'),
    metadata: { disc_size: '4-1/2"', rpm: '8500', included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V Random Orbit Sander Kit',
    slug: '18v-random-orbit-sander-r8606',
    brand: 'Ridgid', category: 'sanders', subcategory: 'random-orbit',
    model: 'R8606', voltage: '18V', price: 8900, compare_price: 10900,
    stock: 14, badge: 'sale', rating: 4.5, review_count: 76,
    description: '12,000 OPM. Micro-filtration dust canister for clean operation.',
    images: img('ridgid','R8606'),
    metadata: { rpm: '12000', included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V Brad Nailer Kit',
    slug: '18v-brad-nailer-r09890b',
    brand: 'Ridgid', category: 'nailers', subcategory: 'brad-nailer',
    model: 'R09890B', voltage: '18V', price: 17900, compare_price: 21900,
    stock: 8, badge: 'sale', rating: 4.6, review_count: 54,
    description: 'Drives 18-gauge brad nails 5/8" to 2". Dry-fire lockout prevents blank firing.',
    images: img('ridgid','R09890B'),
    metadata: { included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V 3-Tool Combo Kit',
    slug: '18v-3-tool-combo-r97400',
    brand: 'Ridgid', category: 'combo', subcategory: '3-tool',
    model: 'R97400', voltage: '18V', price: 27900, compare_price: 33900,
    stock: 9, badge: 'sale', rating: 4.7, review_count: 112,
    description: 'Drill, impact driver, and circular saw. Great value with Lifetime LSA included.',
    images: img('ridgid','R97400'),
    metadata: { included: ['2x 4.0Ah batteries','charger','bag'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '12" Dual Bevel Sliding Compound Miter Saw',
    slug: '12in-miter-saw-r4122',
    brand: 'Ridgid', category: 'saws', subcategory: 'miter-saw',
    model: 'R4122', voltage: 'Corded', price: 42900, compare_price: 49900,
    stock: 4, badge: 'sale', rating: 4.7, review_count: 76,
    description: '15-amp motor. Dual laser guide for accurate cuts. Integrated dust bag.',
    images: img('ridgid','R4122'),
    metadata: { amps: 15, blade_size: '12"', rpm: '4000', warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V Rotary Hammer SDS-Plus Kit',
    slug: '18v-rotary-hammer-r86710b',
    brand: 'Ridgid', category: 'drills', subcategory: 'rotary-hammer',
    model: 'R86710B', voltage: '18V', price: 19900, compare_price: 23900,
    stock: 8, badge: 'sale', rating: 4.6, review_count: 54,
    description: '1.3 ft-lbs impact energy. Vibration control for reduced user fatigue.',
    images: img('ridgid','R86710B'),
    metadata: { rpm: '0-1000', included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },
  {
    name: '18V Jigsaw Kit',
    slug: '18v-jigsaw-r8832b',
    brand: 'Ridgid', category: 'saws', subcategory: 'jigsaw',
    model: 'R8832B', voltage: '18V', price: 9900, compare_price: 12900,
    stock: 12, badge: 'sale', rating: 4.5, review_count: 65,
    description: 'Orbital action 4-position. Variable speed 0-3,200 SPM. LED light for better visibility.',
    images: img('ridgid','R8832B'),
    metadata: { rpm: '0-3200 spm', included: ['2x 4.0Ah batteries','charger'], warranty: 'Lifetime LSA' },
    active: true,
  },

  // ── Ryobi — 9 products ─────────────────────────────────────────────────────

  {
    name: 'ONE+ 18V Brushless Drill/Driver Kit',
    slug: 'one-plus-18v-brushless-drill-psbdd01k',
    brand: 'Ryobi', category: 'drills', subcategory: 'drill-driver',
    model: 'PSBDD01K', voltage: '18V', price: 7900, compare_price: 9900,
    stock: 32, badge: 'sale', rating: 4.5, review_count: 441,
    description: 'Compatible with all 18V ONE+ batteries. 500 in-lbs of torque. Great for DIY and light pro use.',
    images: img('ryobi','PSBDD01K'),
    metadata: { max_torque: '500 in-lbs', rpm: '0-1800', included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ONE+ 18V Circular Saw Kit',
    slug: 'one-plus-18v-circular-saw-pblcs300b',
    brand: 'Ryobi', category: 'saws', subcategory: 'circular-saw',
    model: 'PBLCS300B', voltage: '18V', price: 8900, compare_price: 10900,
    stock: 24, badge: 'sale', rating: 4.4, review_count: 312,
    description: '18V ONE+ brushless 7-1/4" circular saw. 4,700 RPM. Magnesium shoe.',
    images: img('ryobi','PBLCS300B'),
    metadata: { blade_size: '7-1/4"', rpm: '4700', included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ONE+ 18V Impact Driver Kit',
    slug: 'one-plus-18v-impact-driver-pblid01k',
    brand: 'Ryobi', category: 'drills', subcategory: 'impact-driver',
    model: 'PBLID01K', voltage: '18V', price: 6900, compare_price: 8900,
    stock: 36, badge: 'sale', rating: 4.5, review_count: 387,
    description: '1,800 in-lbs of torque. 3-speed selector. ONE+ platform compatible.',
    images: img('ryobi','PBLID01K'),
    metadata: { max_torque: '1800 in-lbs', included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ONE+ 18V Reciprocating Saw Kit',
    slug: 'one-plus-18v-recip-saw-pblrs01k',
    brand: 'Ryobi', category: 'saws', subcategory: 'reciprocating-saw',
    model: 'PBLRS01K', voltage: '18V', price: 7900, compare_price: 9900,
    stock: 18, badge: 'sale', rating: 4.4, review_count: 234,
    description: 'Variable speed 0-3,000 SPM. Anti-vibration technology. Tool-less blade change.',
    images: img('ryobi','PBLRS01K'),
    metadata: { rpm: '0-3000 spm', included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ONE+ 18V 16-Gauge Finish Nailer Kit',
    slug: 'one-plus-18v-finish-nailer-pcl725k1',
    brand: 'Ryobi', category: 'nailers', subcategory: 'finish-nailer',
    model: 'PCL725K1', voltage: '18V', price: 15900, compare_price: 18900,
    stock: 16, badge: 'sale', rating: 4.5, review_count: 213,
    description: 'Drives 16-gauge nails 1" to 2-1/2". Great for trim, molding, and casing.',
    images: img('ryobi','PCL725K1'),
    metadata: { included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ONE+ 18V Random Orbit Sander Kit',
    slug: 'one-plus-18v-random-orbit-sander-pclsv01k',
    brand: 'Ryobi', category: 'sanders', subcategory: 'random-orbit',
    model: 'PCLSV01K', voltage: '18V', price: 5900, compare_price: 7900,
    stock: 29, badge: 'sale', rating: 4.4, review_count: 312,
    description: '12,000 OPM. Dust sealed switch. Micro-filter dust canister.',
    images: img('ryobi','PCLSV01K'),
    metadata: { rpm: '12000', included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ONE+ 18V 4-1/2" Angle Grinder Kit',
    slug: 'one-plus-18v-angle-grinder-pcl810k2',
    brand: 'Ryobi', category: 'grinders', subcategory: 'angle-grinder',
    model: 'PCL810K2', voltage: '18V', price: 7900, compare_price: 9900,
    stock: 21, badge: 'sale', rating: 4.4, review_count: 198,
    description: '8,500 RPM. Tool-less wheel guard adjustment. ONE+ compatible.',
    images: img('ryobi','PCL810K2'),
    metadata: { disc_size: '4-1/2"', rpm: '8500', included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ONE+ 18V 3-Tool Combo Kit',
    slug: 'one-plus-18v-3-tool-combo-pck420b2',
    brand: 'Ryobi', category: 'combo', subcategory: '3-tool',
    model: 'PCK420B2', voltage: '18V', price: 17900, compare_price: 21900,
    stock: 19, badge: 'sale', rating: 4.5, review_count: 287,
    description: 'Drill, impact driver, and circular saw. Best value 3-tool kit on the market.',
    images: img('ryobi','PCK420B2'),
    metadata: { included: ['2x 2.0Ah batteries','charger','bag'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'ONE+ 18V Brad Nailer Kit',
    slug: 'one-plus-18v-brad-nailer-pcl310b2',
    brand: 'Ryobi', category: 'nailers', subcategory: 'brad-nailer',
    model: 'PCL310B2', voltage: '18V', price: 9900, compare_price: 12900,
    stock: 22, badge: 'sale', rating: 4.4, review_count: 198,
    description: 'Drives 18-gauge brad nails 5/8" to 2". Dry-fire lockout and depth adjustment.',
    images: img('ryobi','PCL310B2'),
    metadata: { included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },

  // ── Metabo HPT — 8 products ────────────────────────────────────────────────

  {
    name: '36V MultiVolt 7-1/4" Circular Saw Kit',
    slug: '36v-multivolt-circular-saw-c3607da',
    brand: 'Metabo', category: 'saws', subcategory: 'circular-saw',
    model: 'C3607DA', voltage: '36V', price: 22900, compare_price: null,
    stock: 9, badge: 'new', rating: 4.7, review_count: 65,
    description: 'MultiVolt system accepts both 18V and 36V batteries. 6,000 RPM no-load speed.',
    images: img('metabo','C3607DA'),
    metadata: { blade_size: '7-1/4"', rpm: '6000', included: ['battery','charger'], warranty: '2-year limited' },
    active: true,
  },
  {
    name: '36V MultiVolt Brushless Hammer Drill Kit',
    slug: '36v-multivolt-hammer-drill-dv36daa',
    brand: 'Metabo', category: 'drills', subcategory: 'hammer-drill',
    model: 'DV36DAA', voltage: '36V', price: 21900, compare_price: 25900,
    stock: 7, badge: 'sale', rating: 4.7, review_count: 54,
    description: '1,296 in-lbs of torque. Brush-less motor. 4-mode operation.',
    images: img('metabo','DV36DAA'),
    metadata: { max_torque: '1296 in-lbs', rpm: '0-1800', included: ['battery','charger'], warranty: '2-year limited' },
    active: true,
  },
  {
    name: '36V MultiVolt Impact Driver Kit',
    slug: '36v-multivolt-impact-driver-wh36dbfl2',
    brand: 'Metabo', category: 'drills', subcategory: 'impact-driver',
    model: 'WH36DBL2', voltage: '36V', price: 18900, compare_price: null,
    stock: 8, badge: null, rating: 4.6, review_count: 43,
    description: '4-speed settings. 2,000 in-lbs of torque. Lifetime lithium-ion tool warranty.',
    images: img('metabo','WH36DBL2'),
    metadata: { max_torque: '2000 in-lbs', included: ['battery','charger'], warranty: 'Lifetime tool' },
    active: true,
  },
  {
    name: '36V MultiVolt Reciprocating Saw',
    slug: '36v-multivolt-reciprocating-saw-cr36daa',
    brand: 'Metabo', category: 'saws', subcategory: 'reciprocating-saw',
    model: 'CR36DAA', voltage: '36V', price: 18900, compare_price: 21900,
    stock: 7, badge: 'sale', rating: 4.6, review_count: 43,
    description: 'Variable speed 0-3,000 SPM. Auto-stop when cutting complete.',
    images: img('metabo','CR36DAA'),
    metadata: { rpm: '0-3000 spm', included: ['battery','charger'], warranty: '2-year limited' },
    active: true,
  },
  {
    name: '36V MultiVolt Angle Grinder Kit',
    slug: '36v-multivolt-angle-grinder-g3613da',
    brand: 'Metabo', category: 'grinders', subcategory: 'angle-grinder',
    model: 'G3613DA', voltage: '36V', price: 19900, compare_price: null,
    stock: 8, badge: null, rating: 4.6, review_count: 54,
    description: '8,500 RPM. Auto-stop brake for safer operation.',
    images: img('metabo','G3613DA'),
    metadata: { disc_size: '4-1/2"', rpm: '8500', included: ['battery','charger'], warranty: '2-year limited' },
    active: true,
  },
  {
    name: '36V MultiVolt Brad Nailer',
    slug: '36v-multivolt-brad-nailer-nt1865dbsl',
    brand: 'Metabo', category: 'nailers', subcategory: 'brad-nailer',
    model: 'NT1865DBSL', voltage: '36V', price: 21900, compare_price: null,
    stock: 6, badge: 'new', rating: 4.7, review_count: 32,
    description: 'Drives 18-gauge brad nails. Air spring drive mechanism — no gas needed.',
    images: img('metabo','NT1865DBSL'),
    metadata: { warranty: '2-year limited' },
    active: true,
  },
  {
    name: '36V MultiVolt 2-Tool Combo',
    slug: '36v-multivolt-2-tool-combo-kc36da',
    brand: 'Metabo', category: 'combo', subcategory: '2-tool',
    model: 'KC36DA', voltage: '36V', price: 32900, compare_price: 38900,
    stock: 7, badge: 'sale', rating: 4.7, review_count: 54,
    description: 'Drill and impact driver combo. MultiVolt means one battery works across entire platform.',
    images: img('metabo','KC36DA'),
    metadata: { included: ['2x batteries','charger','bag'], warranty: '2-year limited' },
    active: true,
  },
  {
    name: '36V MultiVolt Jigsaw',
    slug: '36v-multivolt-jigsaw-cj36da',
    brand: 'Metabo', category: 'saws', subcategory: 'jigsaw',
    model: 'CJ36DA', voltage: '36V', price: 16900, compare_price: 19900,
    stock: 7, badge: 'sale', rating: 4.6, review_count: 43,
    description: '4 orbital settings. Variable speed 0-2,800 SPM. Excellent balance.',
    images: img('metabo','CJ36DA'),
    metadata: { rpm: '0-2800 spm', included: ['battery','charger'], warranty: '2-year limited' },
    active: true,
  },

  // ── Craftsman — last products to hit 100 ───────────────────────────────────

  {
    name: 'V20 20V 1/2" Drill/Driver Kit',
    slug: 'v20-20v-drill-driver-cmcd721c2',
    brand: 'Craftsman', category: 'drills', subcategory: 'drill-driver',
    model: 'CMCD721C2', voltage: '20V', price: 6900, compare_price: 8900,
    stock: 38, badge: 'sale', rating: 4.4, review_count: 521,
    description: '350 in-lbs of max torque. 2-speed gearbox. Great for DIYers and homeowners.',
    images: img('craftsman','CMCD721C2'),
    metadata: { max_torque: '350 in-lbs', rpm: '0-1500', included: ['2x 1.5Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'V20 20V Circular Saw Kit',
    slug: 'v20-20v-circular-saw-cmcs550m1',
    brand: 'Craftsman', category: 'saws', subcategory: 'circular-saw',
    model: 'CMCS550M1', voltage: '20V', price: 7900, compare_price: 9900,
    stock: 26, badge: 'sale', rating: 4.3, review_count: 312,
    description: '5,000 RPM. 6-1/2" blade. Bevel capacity 0-50°. Great entry-level cordless saw.',
    images: img('craftsman','CMCS550M1'),
    metadata: { blade_size: '6-1/2"', rpm: '5000', included: ['1x 4.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'V20 20V Impact Driver Kit',
    slug: 'v20-20v-impact-driver-cmcf800d2',
    brand: 'Craftsman', category: 'drills', subcategory: 'impact-driver',
    model: 'CMCF800D2', voltage: '20V', price: 5900, compare_price: 7900,
    stock: 41, badge: 'sale', rating: 4.4, review_count: 456,
    description: '1,460 in-lbs of max torque. 2-speed settings. Compact 5.1" head length.',
    images: img('craftsman','CMCF800D2'),
    metadata: { max_torque: '1460 in-lbs', included: ['2x 2.0Ah batteries','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'V20 20V 4-1/2" Angle Grinder Kit',
    slug: 'v20-20v-angle-grinder-cmcg400m1',
    brand: 'Craftsman', category: 'grinders', subcategory: 'angle-grinder',
    model: 'CMCG400M1', voltage: '20V', price: 6900, compare_price: 8900,
    stock: 23, badge: 'sale', rating: 4.3, review_count: 234,
    description: '7,500 RPM. Spindle lock for easy wheel changes. Tool-free guard adjustment.',
    images: img('craftsman','CMCG400M1'),
    metadata: { disc_size: '4-1/2"', rpm: '7500', included: ['1x 4.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'V20 20V Random Orbit Sander Kit',
    slug: 'v20-20v-random-orbit-sander-cmcsp610m1',
    brand: 'Craftsman', category: 'sanders', subcategory: 'random-orbit',
    model: 'CMCSP610M1', voltage: '20V', price: 4900, compare_price: 6900,
    stock: 31, badge: 'sale', rating: 4.3, review_count: 287,
    description: '11,000 OPM. Dust sealed switch. Micro-filter dust canister. Best value sander.',
    images: img('craftsman','CMCSP610M1'),
    metadata: { rpm: '11000', included: ['1x 2.0Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'V20 20V Brad Nailer Kit',
    slug: 'v20-20v-brad-nailer-cmcn618c1',
    brand: 'Craftsman', category: 'nailers', subcategory: 'brad-nailer',
    model: 'CMCN618C1', voltage: '20V', price: 8900, compare_price: 10900,
    stock: 17, badge: 'sale', rating: 4.4, review_count: 198,
    description: '18-gauge 5/8" to 2" brad nails. Sequential firing mode only. Depth adjustment.',
    images: img('craftsman','CMCN618C1'),
    metadata: { included: ['1x 1.5Ah battery','charger'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: 'V20 20V 3-Tool Combo Kit',
    slug: 'v20-20v-3-tool-combo-cmck700d2',
    brand: 'Craftsman', category: 'combo', subcategory: '3-tool',
    model: 'CMCK700D2', voltage: '20V', price: 14900, compare_price: 18900,
    stock: 22, badge: 'sale', rating: 4.4, review_count: 312,
    description: 'Drill, impact driver, and circular saw. Best value combo kit for homeowners.',
    images: img('craftsman','CMCK700D2'),
    metadata: { included: ['2x 2.0Ah batteries','charger','bag'], warranty: '3-year limited' },
    active: true,
  },
  {
    name: '25ft Tape Measure Classic',
    slug: '25ft-tape-measure-cmht37064s',
    brand: 'Craftsman', category: 'measuring', subcategory: 'tape-measure',
    model: 'CMHT37064S', voltage: 'N/A', price: 1400, compare_price: null,
    stock: 89, badge: null, rating: 4.5, review_count: 1243,
    description: '25ft tape with magnetic tip for solo use. Blade reinforcement reduces breakage.',
    images: img('craftsman','CMHT37064S'),
    metadata: { weight_lbs: 0.8, warranty: 'Lifetime limited' },
    active: true,
  },
]

// ─── Seed function ─────────────────────────────────────────────────────────────

async function seed() {
  console.log(`Seeding ${products.length} products...`)

  // Clear existing products (optional — comment out to append)
  const { error: deleteError } = await supabase
    .from('products')
    .delete()
    .neq('id', '00000000-0000-0000-0000-000000000000')

  if (deleteError) {
    console.error('Error clearing products:', deleteError)
    process.exit(1)
  }

  // Insert in batches of 25
  const BATCH = 25
  for (let i = 0; i < products.length; i += BATCH) {
    const batch = products.slice(i, i + BATCH)
    const { error } = await supabase.from('products').insert(batch)
    if (error) {
      console.error(`Error inserting batch ${i}–${i + BATCH}:`, error)
      process.exit(1)
    }
    console.log(`  ✓ Inserted products ${i + 1}–${Math.min(i + BATCH, products.length)}`)
  }

  console.log(`\n✅ Done! ${products.length} products seeded successfully.`)
  console.log('\nProduct summary:')

  const brands = [...new Set(products.map(p => p.brand))]
  brands.forEach(brand => {
    const count = products.filter(p => p.brand === brand).length
    console.log(`  ${brand}: ${count} products`)
  })

  const cats = [...new Set(products.map(p => p.category))]
  console.log('\nCategory breakdown:')
  cats.forEach(cat => {
    const count = products.filter(p => p.category === cat).length
    console.log(`  ${cat}: ${count} products`)
  })
}

seed().catch(console.error)
